2022-01-25 01:47:29,785 <ERROR> :  occered at executeGetRequest <class 'ValueError'>1
2022-01-25 01:47:29,786 <ERROR> : Traceback (most recent call last):
  File "./py/connect.py", line 207, in executeGetRequest
    root = lxml.html.fromstring(html)
  File "C:\Users\waard\Desktop\my-app\py\env_v3.8.12\lib\site-packages\lxml\html\__init__.py", line 875, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "C:\Users\waard\Desktop\my-app\py\env_v3.8.12\lib\site-packages\lxml\html\__init__.py", line 761, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "src\lxml\etree.pyx", line 3252, in lxml.etree.fromstring
  File "src\lxml\parser.pxi", line 1907, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

2022-01-25 01:48:03,087 <ERROR> :  occered at executeGetRequest requests failed:https://www.jiji.com/jc/c?g=pol
2022-01-25 01:48:06,416 <ERROR> :  occered at executeGetRequest requests failed:https://www.jiji.com/jc/c?g=pol
2022-01-25 01:48:09,727 <ERROR> :  occered at executeGetRequest requests failed:https://www.jiji.com/jc/c?g=pol
2022-01-25 01:48:12,728 <ERROR> :  occered at executeGetRequest Max retries exceeded with urlhttps://www.jiji.com/jc/c?g=pol
